/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.63
 * Generated at: 2022-06-17 05:20:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import kr.ac.ctc.kopo35.Domain.ScoreItem;
import kr.ac.ctc.kopo35.Service.ScoreItemServiceImpl;
import kr.ac.ctc.kopo35.Service.ScoreItemService;
import java.util.List;

public final class selectOne_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("kr.ac.ctc.kopo35.Service.ScoreItemServiceImpl");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("kr.ac.ctc.kopo35.Service.ScoreItemService");
    _jspx_imports_classes.add("kr.ac.ctc.kopo35.Domain.ScoreItem");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"UTF-8\">\r\n");
      out.write("	<title>상세 조회</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "menu.jsp", out, false);
      out.write('\r');
      out.write('\n');
      out.write('	');

		ScoreItemService scoreItemService = new ScoreItemServiceImpl();
		List<ScoreItem> scoreItems = scoreItemService.scoreItemSelectName(request.getParameter("name"));
	
      out.write("\r\n");
      out.write("	<div align=\"center\">\r\n");
      out.write("		<table cellspacing=1 border=1>		<!-- 테이블의 셀간 여백 1, 선 두께 1로 지정 -->\r\n");
      out.write("		<tr height=40px  bgcolor=gray>		<!-- 현재 행의 높이를 40px, 배경색을 회색으로 지정 -->\r\n");
      out.write("			<th width=100px>				<!-- 현재 열의 너비를 100px로 지정 -->\r\n");
      out.write("				이름\r\n");
      out.write("			</th>\r\n");
      out.write("			<th width=100px>				<!-- 현재 열의 너비를 100px로 지정 -->\r\n");
      out.write("				학번\r\n");
      out.write("			</th>\r\n");
      out.write("			<th width=100px>				<!-- 현재 열의 너비를 100px로 지정 -->\r\n");
      out.write("				국어 점수\r\n");
      out.write("			</th>\r\n");
      out.write("			<th width=100px>				<!-- 현재 열의 너비를 100px로 지정 -->\r\n");
      out.write("				영어 점수\r\n");
      out.write("			</th>\r\n");
      out.write("			<th width=100px>				<!-- 현재 열의 너비를 100px로 지정 -->\r\n");
      out.write("				수학 점수\r\n");
      out.write("			</th>\r\n");
      out.write("			</th>\r\n");
      out.write("			<th width=100px>				<!-- 현재 열의 너비를 100px로 지정 -->\r\n");
      out.write("				수정\r\n");
      out.write("			</th>\r\n");
      out.write("			</th>\r\n");
      out.write("			<th width=100px>				<!-- 현재 열의 너비를 100px로 지정 -->\r\n");
      out.write("				삭제\r\n");
      out.write("			</th>\r\n");
      out.write("		</tr>\r\n");
      out.write("		");

			for(ScoreItem scoreItem : scoreItems) {			// ResultSet에 저장된 모든 레코드에 대하여 반복
		
      out.write("\r\n");
      out.write("			<tr height=50px>\r\n");
      out.write("				<td width=50><p align='center'>");
      out.print( scoreItem.getName() );
      out.write("</p></td>\r\n");
      out.write("				<td width=50><p align='center'>");
      out.print( scoreItem.getId() );
      out.write("</p></td>\r\n");
      out.write("				<td width=50><p align='center'>");
      out.print( scoreItem.getKor() );
      out.write("</p></td>\r\n");
      out.write("				<td width=50><p align='center'>");
      out.print( scoreItem.getEng() );
      out.write("</p></td>\r\n");
      out.write("				<td width=50><p align='center'>");
      out.print( scoreItem.getMat() );
      out.write("</p></td>\r\n");
      out.write("				<td width=50>\r\n");
      out.write("					<p align='center'>\r\n");
      out.write("						<button onClick=\"location.href='/ScoreAdmin/updateForm.jsp?id=");
      out.print( scoreItem.getId() );
      out.write("'\">수정</button>\r\n");
      out.write("					</p>\r\n");
      out.write("				</td>\r\n");
      out.write("				<td width=50>\r\n");
      out.write("					<p align='center'>\r\n");
      out.write("						<button onClick=\"location.href='/ScoreAdmin/deleteOne.jsp?id=");
      out.print( scoreItem.getId() );
      out.write("'\">삭제</button>\r\n");
      out.write("					</p>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		");

			}
		
      out.write("\r\n");
      out.write("		</table>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
